### ISSUE TITLE
Add Ability to Change Number of Items Per Page

### ISSUE THREAD

**Issue by prikhi** [elm-community/builtwithelm#108]
Looking through all the projects 5-at-a-time is annoying. It'd be awesome if we added a dropdown that let's us modify the `pageSize` field of the model(and update the URL, now that #104 is merged).

**Comment by lukewestby** [comment]
@prikhi you don't need to make PRs for changes like this, just go ahead and commit to master

**Comment by prikhi** [comment]
@lukewestby Thanks, just dunno when I'll have the time so I figured I'd put it up here as low-hanging fruit.

**Comment by lukewestby** [comment]
@prikhi oh lol i am not with it today, i thought this was a PR. right on, well if you get to it or want to do anything else yeah just push it directly

**Comment by joelclermont** [comment]
This is now live!
