### ISSUE TITLE
No more @luke_dot_js

### ISSUE THREAD

**Issue by BrianHicks** [elm-community/builtwithelm#123]
@lukewestby has left Twitter. The link to his profile remains but 404s.

Options:

- link to twitter.com/ellie_editor
- link to @lukewestby
- remove authorship altogether

**Comment by joelclermont** [comment]
There's also a reference here: https://github.com/elm-community/builtwithelm/blob/master/src/View.elm#L180

**Comment by prikhi** [comment]
Thanks, that one should be fixed now as well.
