### ISSUE TITLE
Fix Travis Build Configuration

### ISSUE THREAD

**Issue by grantschulte** [elm-community/builtwithelm#150]
Travis builds appear to be failing for the last eight pull requests.

[Here is a link](https://github.com/elm-community/builtwithelm/pull/149
) to a failing build that was attempted from my pull request.

The build (and several others) aborts at `No Rakefile found`.

I've noticed that there is no travis configuration file present in the project. Would a proper `.travis.yml` configuration file help to resolve this issue?

**Comment by joelclermont** [comment]
I was just noticing the same thing. It looks like Travis has never successfully built the project. My guess is someone started setting up Travis, but didn't finish.

I've never used Travis, so any help is appreciated :)

**Comment by joelclermont** [comment]
I'm going to start by copying in a Travis config from elm-css and tweaking it a bit. https://github.com/rtfeldman/elm-css/blob/master/.travis.yml

Seems like a good place to start.

**Comment by joelclermont** [comment]
That did the trick. I'm closing this issue, but there is definitely more we could to improve the Travis config:

* add the travis badge to the readme
* do we really need OS X? 
* should we add an elm-format check? 
* add a test runner once #134 is complete?
* integrate what @knewter is working on in #139?
