### ISSUE TITLE
Can't create pull request

### ISSUE THREAD

**Issue by msszczep** [elm-community/builtwithelm#153]
I'm trying to submit an app, but I'm doing this right:

`builtwithelm mitchells$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
builtwithelm mitchells$ git merge triviascoreboard
Updating 62dc067..07cbea9
Fast-forward
 data/images/trivia-scoreboard.png | Bin 0 -> 201891 bytes
 data/projects.json                |   7 +++++++
 2 files changed, 7 insertions(+)
 create mode 100644 data/images/trivia-scoreboard.png
builtwithelm mitchells$ git push
ERROR: Permission to elm-community/builtwithelm.git denied to msszczep.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Help?

**Comment by msszczep** [comment]
Rather, I meant to say: "I'm trying to submit an app, but I'm NOT doing this right:"

**Comment by joelclermont** [comment]
@msszczep You should create a fork of the entire builtwithelm repo, then clone your forked repo and make the changes in a branch off master. You will then have permissions to push that feature branch up to your forked repo. Then go to that branch on your forked repo in Github and there will be an option to create a pull request.

This article might be helpful: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by joelclermont** [comment]
Just to highlight two basic changes from what you originally tried:

* No need to merge to master. Keep your work in a feature branch.
* Push the feature branch to your forked repo, then create a pull request. Don't push to the original repo.

Let me know if I can help further.

**Comment by msszczep** [comment]
Got it.  I missed the create-a-fork-first part.  Done.  

A new pull request is made.  Thanks a million!
