### ISSUE TITLE
Issue with Github Pages Domain?

### ISSUE THREAD

**Issue by prikhi** [elm-community/builtwithelm#180]
I got  this email when I pushed the latest `gh-pages` branch:

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
>
> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.
>
> For information on troubleshooting Jekyll see:
>   https://help.github.com/articles/troubleshooting-jekyll-builds
>
> If you have any questions you can contact us by replying to this email.

Not sure who has control over the DNS for builtwithelm.co, maybe @lukewestby or someone in @elm-community/owners? I also can't access the "Settings" tab for this repository, probably need to be an owner or admin of this repo?

**Comment by lukewestby** [comment]
Looks like GitHub updated the IPs for custom domains. I updated the A records to point to the right places. Try it again in about a minute.

**Comment by prikhi** [comment]
Thanks! `dig` output looks fine now.

**Comment by Gexos** [comment]
Can somebody tell me the correct IP address.

**Comment by cortylal** [comment]
> Can somebody tell me the correct IP address.

According to https://help.github.com/en/articles/troubleshooting-custom-domains#dns-configuration-errors it should be:
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

**Comment by Gexos** [comment]
> 
> 
> > Can somebody tell me the correct IP address.
> 
> According to https://help.github.com/en/articles/troubleshooting-custom-domains#dns-configuration-errors it should be:
> 185.199.108.153
> 185.199.109.153
> 185.199.110.153
> 185.199.111.153

Thank you very much my friend

**Comment by theredpea** [comment]
Newer link
https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-records-with-your-dns-provider

**Comment by Satish-yadav01** [comment]
is it important to give name the same as <username>.github.io
or can we put another name to the repo.
please help me

**Comment by djGrill** [comment]
Here's the list of `IP addresses`:

https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
