### ISSUE TITLE
identifying open source projects?

### ISSUE THREAD

**Issue by BKSpurgeon** [elm-community/builtwithelm#184]
Thank you for this site.

My question: is there any way of easily identifying whether the listed projects are open source or not?

chrs

**Comment by joelclermont** [comment]
Each project has an optional `repositoryUrl` value in [`data/projects.json`](https://github.com/elm-community/builtwithelm/blob/master/data/projects.json). If this value is present, we show a Github icon in the upper right of the project section on the site:
<img width="937" alt="Screen Shot 2019-08-25 at 8 27 39 AM" src="https://user-images.githubusercontent.com/298100/63650635-43106f00-c712-11e9-84a2-7d8da70a7fef.png">

If it's `null`, we omit the icon:
<img width="902" alt="Screen Shot 2019-08-25 at 8 27 46 AM" src="https://user-images.githubusercontent.com/298100/63650639-4d326d80-c712-11e9-990b-0a195086c201.png">

This doesn't 100% correspond to "open source", depending on what you mean, but it's a quick indication as to whether or not the author has included a link to a source code repository or not. Does that help?

**Comment by BKSpurgeon** [comment]
@joelclermont that is absolutely perfect. Thank you!
