### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by lukewestby** [elm-community/builtwithelm#20]
builtwithelm is going to be listed on elm-lang.org! In anticipation of an increase in the number of listed projects I'd like to paginate the list 5 projects at a time in order of most recently added, i.e. page one contains the latest through fifth-latest projects to join. Let's continue to load the entire JSON list at once at startup of the app. The main purpose of this change is to keep the page weight low due to all the large images.

I would prefer that someone who is new to Elm contribute this feature, and I'll offer personal guidance to anyone that needs it :smile:

**Comment by Bipsy** [comment]
I'd love to give this a shot. I'm building my first Elm app at the moment and I would love to have some assisted learning.

**Comment by lukewestby** [comment]
@Bipsy it's all yours! Are you a member of the elmlang slack? That's my preferred means of RT communication for Elm stuff.

**Comment by lukewestby** [comment]
@Bipsy any issues getting started on this?

**Comment by Bipsy** [comment]
@lukewestby
I was expecting a notification when you responded to my comment. My apologies. I just saw your response. I'll get started on it tonight.

On the Elm slack I'm Bipvanwinkle

**Comment by lukewestby** [comment]
@Bipsy no worries! Let me know if you need anything at all.

**Comment by lukewestby** [comment]
All set! #22
