### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by lukewestby** [elm-community/builtwithelm#25]
Idk anything about site analytics, and I'd also really like whatever analytics do go on the site to be as transparent as possible. If anyone knows anything about doing this I would love some advice.

The reason for this interest is that builtwithelm got a really awesome mention [here](http://elm-lang.org/blog/new-adventures-for-elm) today and I would have loved to see if it's gotten more folks to check out the site and consider posting their projects.

**Comment by joelclermont** [comment]
What do you mean by transparent? Just something super easy to install and use? Something like Google Analytics would be incredibly easy to drop in, but it's a third party, so I'm not sure if you're open to that.

**Comment by lukewestby** [comment]
this feels not so important anymore, i'm gonna close it
