### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by lukewestby** [elm-community/builtwithelm#4]
- [x] Make an attempt at using elm-css for styles
  - #50 
- [x] Make the site responsive
  - #50 
- [x] I did a terrible job optimizing the images for the elm-lang entries, despite my own advice
  - #24

**Comment by jbalboni** [comment]
@lukewestby I was using this site to try out elm-css and I have it pretty much converted (along with making it responsive). Are you interested in a PR for that? I wanted to ask first since I think it'll be a fairly large one.

**Comment by lukewestby** [comment]
:tada: :tada: :tada: :tada: yes, please submit a PR! Thank you!!

**Comment by lukewestby** [comment]
done! thanks to @jbalboni
