### ISSUE TITLE
New project : Stellaris race maker

### ISSUE THREAD

**Issue by kaisersly** [elm-community/builtwithelm#57]
name : Stellaris race maker
previewImageUrl : https://raw.githubusercontent.com/kaisersly/stellaris_race_maker/master/preview.png
primaryUrl : http://kaisersly.github.io/stellaris_race_maker
repositoryUrl : https://github.com/kaisersly/stellaris_race_maker
description : An ugly tool to let you make your own race in Stellaris, the 4X from Paradox (Crusader Kings, Europa Universalis, ...).

**Comment by lukewestby** [comment]
Hey @kaisersly, can you submit a PR with your image and data included? Thanks!
