### ISSUE TITLE
Images linger after page change

### ISSUE THREAD

**Issue by ktosiek** [elm-community/builtwithelm#66]
on a slow enough connection you can see old images being still shown (with new text) after changing a page. It looks like the app changes img's src instead of replacing the whole element.

**Comment by lukewestby** [comment]
yep, i've been noticing this for a while. not sure what the best way to fix it is yet. i'll leave this open until we can come up with something.

**Comment by ktosiek** [comment]
Looks like the Html.Keyed API in elm-html 1.1.0 should help here, I'll try this later today
